name: CoarseGrainedVQE
dependencies:
  - python>=3.5
  - pip>=19
  - matplotlib
  - notebook
  - ipywidgets
  - pip:
    - scikit-learn
    - retworkx
    - qiskit
    - qiskit-nature
    - qiskit-aer
    - qiskit-ignis
    - qiskit-ibm-provider
    - pylatexenc
    - mpltex
    - graycode
